name: CI/CD for VS Code Plugin
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - uses: lannonbr/vsce-action@4.0.0
        with:
          args: "publish -p $VSCE_PAT"
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}